/* Generated by AN DISI Unibo */ 
package it.unibo.serviceaccessgui

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Serviceaccessgui ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		 
				var Ticket= " "
				var Ticketok= false 
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						CommUtils.outcyan("ACCESSGUI : attende")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s1", cond=doswitch() )
				}	 
				state("s1") { //this:State
					action { //it:State
						request("depositRequest", "depositRequest(NO_PARAM)" ,"coldstorageservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="indoor",cond=whenReply("accept"))
					transition(edgeName="t03",targetState="trylater",cond=whenReply("reject"))
				}	 
				state("trylater") { //this:State
					action { //it:State
						CommUtils.outred("ACCESSGUI: rifiutato")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_trylater", 
				 	 					  scope, context!!, "local_tout_"+name+"_trylater", 5000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="wait4",targetState="s1",cond=whenTimeout("local_tout_"+name+"_trylater"))   
				}	 
				state("indoor") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("accept(TICKET)"), Term.createTerm("accept(TICKET)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Ticket = payloadArg(0) 
								CommUtils.outgreen("ACCESSGUI: ticket accettato, Ticket : $Ticket ")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_indoor", 
				 	 					  scope, context!!, "local_tout_"+name+"_indoor", 3000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t25",targetState="giveticket",cond=whenTimeout("local_tout_"+name+"_indoor"))   
				}	 
				state("giveticket") { //this:State
					action { //it:State
						CommUtils.outcyan("ACCESSGUI: consegno ticket ")
						request("checkmyticket", "checkmyticket($Ticket)" ,"coldstorageservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="tc6",targetState="checkresponse",cond=whenReply("ticketcheck"))
				}	 
				state("checkresponse") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("ticketcheck(BOOL)"), Term.createTerm("ticketcheck(BOOL)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Ticketok = payloadArg(0).toBoolean()  
						}
						CommUtils.outcyan("ACCESSGUI: biglietto accettato? : $Ticketok")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s1", cond=doswitchGuarded({!Ticketok 
					}) )
					transition( edgeName="goto",targetState="unloading", cond=doswitchGuarded({! (!Ticketok 
					) }) )
				}	 
				state("unloading") { //this:State
					action { //it:State
						CommUtils.outyellow("ACCESSGUI: effettua scarico")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s1", cond=doswitch() )
				}	 
			}
		}
} 
