/* Generated by AN DISI Unibo */ 
package it.unibo.transporttrolley

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Transporttrolley ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("TRANSPORTTROLLEY:  attivo!")
						CommUtils.outblue("TRANSPORTTROLLEY:  engage basicrobot")
						request("engage", "engage(transporttrolley,305)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s1", cond=doswitch() )
				}	 
				state("s1") { //this:State
					action { //it:State
						CommUtils.outblue("TRANSPORTTROLLEY: sono in HOME, attendo messaggi da CStorage.")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t013",targetState="goIndoor",cond=whenRequest("takecharge"))
					transition(edgeName="t014",targetState="quit",cond=whenRequest("quit"))
				}	 
				state("goIndoor") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("takecharge(NO_PARAM)"), Term.createTerm("takecharge(NO_PARAM)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outblue("TRANSPORTTROLLEY: vado in INDOOR e prendo il carico. ")
								answer("takecharge", "chargetaken", "chargetaken(NO_PARAM)"   )  
						}
						request("moverobot", "moverobot(0,4)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t115",targetState="carica",cond=whenReply("moverobotdone"))
				}	 
				state("carica") { //this:State
					action { //it:State
						
								println("TRANSPORTTROLLEY: sto prendendo il carico .")
							    var  Duration= Math.floor(Math.random() *2500).toLong()
							    delay(Duration)
						CommUtils.outblue("TRANSPORTTROLLEY: vado verso COLDROOM")
						request("moverobot", "moverobot(4,3)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t216",targetState="raggiuntoCR",cond=whenReply("moverobotdone"))
				}	 
				state("raggiuntoCR") { //this:State
					action { //it:State
						
								println("TRANSPORTTROLLEY: sto caricando il frigo.")
							    var  Duration= Math.floor(Math.random() *4500).toLong()
							    delay(Duration)
						CommUtils.outblue("TRANSPORTTROLLEY: ho caricato il frigo.")
						forward("liberoTT", "liberoTT(NO_PARAM)" ,"coldstorageservice" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t317",targetState="goIndoor",cond=whenRequest("takecharge"))
					transition(edgeName="t318",targetState="vaiCasa",cond=whenDispatch("goHome"))
					transition(edgeName="t319",targetState="quit",cond=whenRequest("quit"))
				}	 
				state("vaiCasa") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("goHome(NO_PARAM)"), Term.createTerm("goHome(NO_PARAM)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outblue("TRANSPORTTROLLEY: vado in HOME.")
						}
						request("moverobot", "moverobot(0,0)" ,"basicrobot" )  
						forward("setdirection", "dir(down)" ,"basicrobot" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t420",targetState="s1",cond=whenReply("moverobotdone"))
					transition(edgeName="t421",targetState="quit",cond=whenRequest("quit"))
				}	 
				state("quit") { //this:State
					action { //it:State
						request("moverobot", "moverobot(0,0)" ,"basicrobot" )  
						forward("setdirection", "dir(down)" ,"basicrobot" ) 
						forward("disengage", "disengage(transporttrolley)" ,"basicrobot" ) 
						CommUtils.outblue("TRANSPORTTROLLEY:  disengage basicrobot")
						 System.exit(0)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
